CREATE TABLE NEW_CERTIFICATE(
    ID NUMBER(10,0) NOT NULL ENABLE,
    CERTIFICATE_NAME VARCHAR2(30),
    CONSTRAINT NEW_CERTIFICATE_PK PRIMARY KEY (ID)   
);

CREATE SEQUENCE  new_certificate_id_sequence;
